version: 2.1

jobs:
  build-macos:
    macos:
      xcode: "14.2.0"
    working_directory: /tmp
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build Electron app for macOS M1
          command: npm run make -- --arch=arm64
      - store_artifacts:
          path: /tmp/art-1
          destination: artifact-file
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2
  build:
    jobs:
      - build-macos
